//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
// 
#pragma warning disable 1591

namespace ApplicationUtils.PromovaErrorService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;

	//public partial class PromovaService : Microsoft.Web.Services3.WebServicesClientProtocol{
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PromovaServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ErrorShortInfo[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SummaryItem[]))]
    public partial class PromovaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorSumaryListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorListByFieldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorListByFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorSumaryListByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorSumaryListByTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorSumaryListByCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorSumaryListByWhereClauseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetXmlFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadXmlFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DowloadErrorFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadErrorFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveErrorToTrashOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveErrorToTrash2OperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteError2OperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertErrorFileInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertSummarỵ̣̣̣̣̣̣̣OperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMaxRequestLengthOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertSummaryInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PromovaService() {
            this.Url = global::ApplicationUtils.Properties.Settings.Default.ApplicationUtils_GKErrorService_GKService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event GetErrorSumaryListCompletedEventHandler GetErrorSumaryListCompleted;
        
        /// <remarks/>
        public event GetErrorListByFieldCompletedEventHandler GetErrorListByFieldCompleted;
        
        /// <remarks/>
        public event GetErrorListByFieldsCompletedEventHandler GetErrorListByFieldsCompleted;
        
        /// <remarks/>
        public event GetErrorInfoCompletedEventHandler GetErrorInfoCompleted;
        
        /// <remarks/>
        public event GetErrorFilesCompletedEventHandler GetErrorFilesCompleted;
        
        /// <remarks/>
        public event GetErrorSumaryListByDateCompletedEventHandler GetErrorSumaryListByDateCompleted;
        
        /// <remarks/>
        public event GetErrorSumaryListByTypeCompletedEventHandler GetErrorSumaryListByTypeCompleted;
        
        /// <remarks/>
        public event GetErrorSumaryListByCustomerCompletedEventHandler GetErrorSumaryListByCustomerCompleted;
        
        /// <remarks/>
        public event GetErrorSumaryListByWhereClauseCompletedEventHandler GetErrorSumaryListByWhereClauseCompleted;
        
        /// <remarks/>
        public event GetXmlFileCompletedEventHandler GetXmlFileCompleted;
        
        /// <remarks/>
        public event UploadXmlFileCompletedEventHandler UploadXmlFileCompleted;
        
        /// <remarks/>
        public event DowloadErrorFileCompletedEventHandler DowloadErrorFileCompleted;
        
        /// <remarks/>
        public event UploadErrorFileCompletedEventHandler UploadErrorFileCompleted;
        
        /// <remarks/>
        public event MoveErrorToTrashCompletedEventHandler MoveErrorToTrashCompleted;
        
        /// <remarks/>
        public event MoveErrorToTrash2CompletedEventHandler MoveErrorToTrash2Completed;
        
        /// <remarks/>
        public event DeleteErrorCompletedEventHandler DeleteErrorCompleted;
        
        /// <remarks/>
        public event DeleteError2CompletedEventHandler DeleteError2Completed;
        
        /// <remarks/>
        public event InsertErrorCompletedEventHandler InsertErrorCompleted;
        
        /// <remarks/>
        public event InsertErrorFileInfoCompletedEventHandler InsertErrorFileInfoCompleted;
        
        /// <remarks/>
        public event InsertSummarỵ̣̣̣̣̣̣̣CompletedEventHandler InsertSummarỵ̣̣̣̣̣̣̣Completed;
        
        /// <remarks/>
        public event CreateErrorCompletedEventHandler CreateErrorCompleted;
        
        /// <remarks/>
        public event GetMaxRequestLengthCompletedEventHandler GetMaxRequestLengthCompleted;
        
        /// <remarks/>
        public event InsertSummaryInfoCompletedEventHandler InsertSummaryInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string userName, string pass) {
            object[] results = this.Invoke("Login", new object[] {
                        userName,
                        pass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string userName, string pass) {
            this.LoginAsync(userName, pass, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string userName, string pass, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        userName,
                        pass}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorSumaryList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorShortInfo[] GetErrorSumaryList() {
            object[] results = this.Invoke("GetErrorSumaryList", new object[0]);
            return ((ErrorShortInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorSumaryListAsync() {
            this.GetErrorSumaryListAsync(null);
        }
        
        /// <remarks/>
        public void GetErrorSumaryListAsync(object userState) {
            if ((this.GetErrorSumaryListOperationCompleted == null)) {
                this.GetErrorSumaryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorSumaryListOperationCompleted);
            }
            this.InvokeAsync("GetErrorSumaryList", new object[0], this.GetErrorSumaryListOperationCompleted, userState);
        }
        
        private void OnGetErrorSumaryListOperationCompleted(object arg) {
            if ((this.GetErrorSumaryListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorSumaryListCompleted(this, new GetErrorSumaryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorListByField", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorShortInfo[] GetErrorListByField(string fieldName, string fieldValue) {
            object[] results = this.Invoke("GetErrorListByField", new object[] {
                        fieldName,
                        fieldValue});
            return ((ErrorShortInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorListByFieldAsync(string fieldName, string fieldValue) {
            this.GetErrorListByFieldAsync(fieldName, fieldValue, null);
        }
        
        /// <remarks/>
        public void GetErrorListByFieldAsync(string fieldName, string fieldValue, object userState) {
            if ((this.GetErrorListByFieldOperationCompleted == null)) {
                this.GetErrorListByFieldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorListByFieldOperationCompleted);
            }
            this.InvokeAsync("GetErrorListByField", new object[] {
                        fieldName,
                        fieldValue}, this.GetErrorListByFieldOperationCompleted, userState);
        }
        
        private void OnGetErrorListByFieldOperationCompleted(object arg) {
            if ((this.GetErrorListByFieldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorListByFieldCompleted(this, new GetErrorListByFieldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorListByFields", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorShortInfo[] GetErrorListByFields(string[] fieldName, string[] fieldValue) {
            object[] results = this.Invoke("GetErrorListByFields", new object[] {
                        fieldName,
                        fieldValue});
            return ((ErrorShortInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorListByFieldsAsync(string[] fieldName, string[] fieldValue) {
            this.GetErrorListByFieldsAsync(fieldName, fieldValue, null);
        }
        
        /// <remarks/>
        public void GetErrorListByFieldsAsync(string[] fieldName, string[] fieldValue, object userState) {
            if ((this.GetErrorListByFieldsOperationCompleted == null)) {
                this.GetErrorListByFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorListByFieldsOperationCompleted);
            }
            this.InvokeAsync("GetErrorListByFields", new object[] {
                        fieldName,
                        fieldValue}, this.GetErrorListByFieldsOperationCompleted, userState);
        }
        
        private void OnGetErrorListByFieldsOperationCompleted(object arg) {
            if ((this.GetErrorListByFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorListByFieldsCompleted(this, new GetErrorListByFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorInfo GetErrorInfo(string errorId) {
            object[] results = this.Invoke("GetErrorInfo", new object[] {
                        errorId});
            return ((ErrorInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorInfoAsync(string errorId) {
            this.GetErrorInfoAsync(errorId, null);
        }
        
        /// <remarks/>
        public void GetErrorInfoAsync(string errorId, object userState) {
            if ((this.GetErrorInfoOperationCompleted == null)) {
                this.GetErrorInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorInfoOperationCompleted);
            }
            this.InvokeAsync("GetErrorInfo", new object[] {
                        errorId}, this.GetErrorInfoOperationCompleted, userState);
        }
        
        private void OnGetErrorInfoOperationCompleted(object arg) {
            if ((this.GetErrorInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorInfoCompleted(this, new GetErrorInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorFiles GetErrorFiles(string errorId) {
            object[] results = this.Invoke("GetErrorFiles", new object[] {
                        errorId});
            return ((ErrorFiles)(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorFilesAsync(string errorId) {
            this.GetErrorFilesAsync(errorId, null);
        }
        
        /// <remarks/>
        public void GetErrorFilesAsync(string errorId, object userState) {
            if ((this.GetErrorFilesOperationCompleted == null)) {
                this.GetErrorFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorFilesOperationCompleted);
            }
            this.InvokeAsync("GetErrorFiles", new object[] {
                        errorId}, this.GetErrorFilesOperationCompleted, userState);
        }
        
        private void OnGetErrorFilesOperationCompleted(object arg) {
            if ((this.GetErrorFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorFilesCompleted(this, new GetErrorFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorSumaryListByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorShortInfo[] GetErrorSumaryListByDate(System.DateTime formDate, System.DateTime toDate) {
            object[] results = this.Invoke("GetErrorSumaryListByDate", new object[] {
                        formDate,
                        toDate});
            return ((ErrorShortInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorSumaryListByDateAsync(System.DateTime formDate, System.DateTime toDate) {
            this.GetErrorSumaryListByDateAsync(formDate, toDate, null);
        }
        
        /// <remarks/>
        public void GetErrorSumaryListByDateAsync(System.DateTime formDate, System.DateTime toDate, object userState) {
            if ((this.GetErrorSumaryListByDateOperationCompleted == null)) {
                this.GetErrorSumaryListByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorSumaryListByDateOperationCompleted);
            }
            this.InvokeAsync("GetErrorSumaryListByDate", new object[] {
                        formDate,
                        toDate}, this.GetErrorSumaryListByDateOperationCompleted, userState);
        }
        
        private void OnGetErrorSumaryListByDateOperationCompleted(object arg) {
            if ((this.GetErrorSumaryListByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorSumaryListByDateCompleted(this, new GetErrorSumaryListByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorSumaryListByType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorShortInfo[] GetErrorSumaryListByType(string typeName) {
            object[] results = this.Invoke("GetErrorSumaryListByType", new object[] {
                        typeName});
            return ((ErrorShortInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorSumaryListByTypeAsync(string typeName) {
            this.GetErrorSumaryListByTypeAsync(typeName, null);
        }
        
        /// <remarks/>
        public void GetErrorSumaryListByTypeAsync(string typeName, object userState) {
            if ((this.GetErrorSumaryListByTypeOperationCompleted == null)) {
                this.GetErrorSumaryListByTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorSumaryListByTypeOperationCompleted);
            }
            this.InvokeAsync("GetErrorSumaryListByType", new object[] {
                        typeName}, this.GetErrorSumaryListByTypeOperationCompleted, userState);
        }
        
        private void OnGetErrorSumaryListByTypeOperationCompleted(object arg) {
            if ((this.GetErrorSumaryListByTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorSumaryListByTypeCompleted(this, new GetErrorSumaryListByTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorSumaryListByCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorShortInfo[] GetErrorSumaryListByCustomer(string installationName) {
            object[] results = this.Invoke("GetErrorSumaryListByCustomer", new object[] {
                        installationName});
            return ((ErrorShortInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorSumaryListByCustomerAsync(string installationName) {
            this.GetErrorSumaryListByCustomerAsync(installationName, null);
        }
        
        /// <remarks/>
        public void GetErrorSumaryListByCustomerAsync(string installationName, object userState) {
            if ((this.GetErrorSumaryListByCustomerOperationCompleted == null)) {
                this.GetErrorSumaryListByCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorSumaryListByCustomerOperationCompleted);
            }
            this.InvokeAsync("GetErrorSumaryListByCustomer", new object[] {
                        installationName}, this.GetErrorSumaryListByCustomerOperationCompleted, userState);
        }
        
        private void OnGetErrorSumaryListByCustomerOperationCompleted(object arg) {
            if ((this.GetErrorSumaryListByCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorSumaryListByCustomerCompleted(this, new GetErrorSumaryListByCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorSumaryListByWhereClause", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorShortInfo[] GetErrorSumaryListByWhereClause(string whereClause) {
            object[] results = this.Invoke("GetErrorSumaryListByWhereClause", new object[] {
                        whereClause});
            return ((ErrorShortInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorSumaryListByWhereClauseAsync(string whereClause) {
            this.GetErrorSumaryListByWhereClauseAsync(whereClause, null);
        }
        
        /// <remarks/>
        public void GetErrorSumaryListByWhereClauseAsync(string whereClause, object userState) {
            if ((this.GetErrorSumaryListByWhereClauseOperationCompleted == null)) {
                this.GetErrorSumaryListByWhereClauseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorSumaryListByWhereClauseOperationCompleted);
            }
            this.InvokeAsync("GetErrorSumaryListByWhereClause", new object[] {
                        whereClause}, this.GetErrorSumaryListByWhereClauseOperationCompleted, userState);
        }
        
        private void OnGetErrorSumaryListByWhereClauseOperationCompleted(object arg) {
            if ((this.GetErrorSumaryListByWhereClauseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorSumaryListByWhereClauseCompleted(this, new GetErrorSumaryListByWhereClauseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetXmlFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetXmlFile(string errorId) {
            object[] results = this.Invoke("GetXmlFile", new object[] {
                        errorId});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetXmlFileAsync(string errorId) {
            this.GetXmlFileAsync(errorId, null);
        }
        
        /// <remarks/>
        public void GetXmlFileAsync(string errorId, object userState) {
            if ((this.GetXmlFileOperationCompleted == null)) {
                this.GetXmlFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXmlFileOperationCompleted);
            }
            this.InvokeAsync("GetXmlFile", new object[] {
                        errorId}, this.GetXmlFileOperationCompleted, userState);
        }
        
        private void OnGetXmlFileOperationCompleted(object arg) {
            if ((this.GetXmlFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXmlFileCompleted(this, new GetXmlFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadXmlFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadXmlFile(string errorId, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] content) {
            object[] results = this.Invoke("UploadXmlFile", new object[] {
                        errorId,
                        content});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadXmlFileAsync(string errorId, byte[] content) {
            this.UploadXmlFileAsync(errorId, content, null);
        }
        
        /// <remarks/>
        public void UploadXmlFileAsync(string errorId, byte[] content, object userState) {
            if ((this.UploadXmlFileOperationCompleted == null)) {
                this.UploadXmlFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadXmlFileOperationCompleted);
            }
            this.InvokeAsync("UploadXmlFile", new object[] {
                        errorId,
                        content}, this.UploadXmlFileOperationCompleted, userState);
        }
        
        private void OnUploadXmlFileOperationCompleted(object arg) {
            if ((this.UploadXmlFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadXmlFileCompleted(this, new UploadXmlFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DowloadErrorFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DowloadErrorFile(string errorId, string fileName) {
            object[] results = this.Invoke("DowloadErrorFile", new object[] {
                        errorId,
                        fileName});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DowloadErrorFileAsync(string errorId, string fileName) {
            this.DowloadErrorFileAsync(errorId, fileName, null);
        }
        
        /// <remarks/>
        public void DowloadErrorFileAsync(string errorId, string fileName, object userState) {
            if ((this.DowloadErrorFileOperationCompleted == null)) {
                this.DowloadErrorFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDowloadErrorFileOperationCompleted);
            }
            this.InvokeAsync("DowloadErrorFile", new object[] {
                        errorId,
                        fileName}, this.DowloadErrorFileOperationCompleted, userState);
        }
        
        private void OnDowloadErrorFileOperationCompleted(object arg) {
            if ((this.DowloadErrorFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DowloadErrorFileCompleted(this, new DowloadErrorFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadErrorFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadErrorFile(string fileName, ErrorInfo errorInfo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] content) {
            object[] results = this.Invoke("UploadErrorFile", new object[] {
                        fileName,
                        errorInfo,
                        content});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadErrorFileAsync(string fileName, ErrorInfo errorInfo, byte[] content) {
            this.UploadErrorFileAsync(fileName, errorInfo, content, null);
        }
        
        /// <remarks/>
        public void UploadErrorFileAsync(string fileName, ErrorInfo errorInfo, byte[] content, object userState) {
            if ((this.UploadErrorFileOperationCompleted == null)) {
                this.UploadErrorFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadErrorFileOperationCompleted);
            }
            this.InvokeAsync("UploadErrorFile", new object[] {
                        fileName,
                        errorInfo,
                        content}, this.UploadErrorFileOperationCompleted, userState);
        }
        
        private void OnUploadErrorFileOperationCompleted(object arg) {
            if ((this.UploadErrorFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadErrorFileCompleted(this, new UploadErrorFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MoveErrorToTrash", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MoveErrorToTrash(string errorId) {
            object[] results = this.Invoke("MoveErrorToTrash", new object[] {
                        errorId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MoveErrorToTrashAsync(string errorId) {
            this.MoveErrorToTrashAsync(errorId, null);
        }
        
        /// <remarks/>
        public void MoveErrorToTrashAsync(string errorId, object userState) {
            if ((this.MoveErrorToTrashOperationCompleted == null)) {
                this.MoveErrorToTrashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveErrorToTrashOperationCompleted);
            }
            this.InvokeAsync("MoveErrorToTrash", new object[] {
                        errorId}, this.MoveErrorToTrashOperationCompleted, userState);
        }
        
        private void OnMoveErrorToTrashOperationCompleted(object arg) {
            if ((this.MoveErrorToTrashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveErrorToTrashCompleted(this, new MoveErrorToTrashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MoveErrorToTrash2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MoveErrorToTrash2(string[] errorIds) {
            object[] results = this.Invoke("MoveErrorToTrash2", new object[] {
                        errorIds});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MoveErrorToTrash2Async(string[] errorIds) {
            this.MoveErrorToTrash2Async(errorIds, null);
        }
        
        /// <remarks/>
        public void MoveErrorToTrash2Async(string[] errorIds, object userState) {
            if ((this.MoveErrorToTrash2OperationCompleted == null)) {
                this.MoveErrorToTrash2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveErrorToTrash2OperationCompleted);
            }
            this.InvokeAsync("MoveErrorToTrash2", new object[] {
                        errorIds}, this.MoveErrorToTrash2OperationCompleted, userState);
        }
        
        private void OnMoveErrorToTrash2OperationCompleted(object arg) {
            if ((this.MoveErrorToTrash2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveErrorToTrash2Completed(this, new MoveErrorToTrash2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteError(string errorId) {
            object[] results = this.Invoke("DeleteError", new object[] {
                        errorId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteErrorAsync(string errorId) {
            this.DeleteErrorAsync(errorId, null);
        }
        
        /// <remarks/>
        public void DeleteErrorAsync(string errorId, object userState) {
            if ((this.DeleteErrorOperationCompleted == null)) {
                this.DeleteErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteErrorOperationCompleted);
            }
            this.InvokeAsync("DeleteError", new object[] {
                        errorId}, this.DeleteErrorOperationCompleted, userState);
        }
        
        private void OnDeleteErrorOperationCompleted(object arg) {
            if ((this.DeleteErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteErrorCompleted(this, new DeleteErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteError2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteError2(string[] errorIds) {
            object[] results = this.Invoke("DeleteError2", new object[] {
                        errorIds});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteError2Async(string[] errorIds) {
            this.DeleteError2Async(errorIds, null);
        }
        
        /// <remarks/>
        public void DeleteError2Async(string[] errorIds, object userState) {
            if ((this.DeleteError2OperationCompleted == null)) {
                this.DeleteError2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteError2OperationCompleted);
            }
            this.InvokeAsync("DeleteError2", new object[] {
                        errorIds}, this.DeleteError2OperationCompleted, userState);
        }
        
        private void OnDeleteError2OperationCompleted(object arg) {
            if ((this.DeleteError2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteError2Completed(this, new DeleteError2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorInfo InsertError(ErrorInfo errorInfo) {
            object[] results = this.Invoke("InsertError", new object[] {
                        errorInfo});
            return ((ErrorInfo)(results[0]));
        }
        
        /// <remarks/>
        public void InsertErrorAsync(ErrorInfo errorInfo) {
            this.InsertErrorAsync(errorInfo, null);
        }
        
        /// <remarks/>
        public void InsertErrorAsync(ErrorInfo errorInfo, object userState) {
            if ((this.InsertErrorOperationCompleted == null)) {
                this.InsertErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertErrorOperationCompleted);
            }
            this.InvokeAsync("InsertError", new object[] {
                        errorInfo}, this.InsertErrorOperationCompleted, userState);
        }
        
        private void OnInsertErrorOperationCompleted(object arg) {
            if ((this.InsertErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertErrorCompleted(this, new InsertErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertErrorFileInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertErrorFileInfo(string errorId, ErrorFileInfo errorFileInfo) {
            this.Invoke("InsertErrorFileInfo", new object[] {
                        errorId,
                        errorFileInfo});
        }
        
        /// <remarks/>
        public void InsertErrorFileInfoAsync(string errorId, ErrorFileInfo errorFileInfo) {
            this.InsertErrorFileInfoAsync(errorId, errorFileInfo, null);
        }
        
        /// <remarks/>
        public void InsertErrorFileInfoAsync(string errorId, ErrorFileInfo errorFileInfo, object userState) {
            if ((this.InsertErrorFileInfoOperationCompleted == null)) {
                this.InsertErrorFileInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertErrorFileInfoOperationCompleted);
            }
            this.InvokeAsync("InsertErrorFileInfo", new object[] {
                        errorId,
                        errorFileInfo}, this.InsertErrorFileInfoOperationCompleted, userState);
        }
        
        private void OnInsertErrorFileInfoOperationCompleted(object arg) {
            if ((this.InsertErrorFileInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertErrorFileInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertSummarỵ̣̣̣̣̣̣̣", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertSummarỵ̣̣̣̣̣̣̣(string errorId, System.Data.DataSet summaryInfo) {
            object[] results = this.Invoke("InsertSummarỵ̣̣̣̣̣̣̣", new object[] {
                        errorId,
                        summaryInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertSummarỵ̣̣̣̣̣̣̣Async(string errorId, System.Data.DataSet summaryInfo) {
            this.InsertSummarỵ̣̣̣̣̣̣̣Async(errorId, summaryInfo, null);
        }
        
        /// <remarks/>
        public void InsertSummarỵ̣̣̣̣̣̣̣Async(string errorId, System.Data.DataSet summaryInfo, object userState) {
            if ((this.InsertSummarỵ̣̣̣̣̣̣̣OperationCompleted == null)) {
                this.InsertSummarỵ̣̣̣̣̣̣̣OperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertSummarỵ̣̣̣̣̣̣̣OperationCompleted);
            }
            this.InvokeAsync("InsertSummarỵ̣̣̣̣̣̣̣", new object[] {
                        errorId,
                        summaryInfo}, this.InsertSummarỵ̣̣̣̣̣̣̣OperationCompleted, userState);
        }
        
        private void OnInsertSummarỵ̣̣̣̣̣̣̣OperationCompleted(object arg) {
            if ((this.InsertSummarỵ̣̣̣̣̣̣̣Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertSummarỵ̣̣̣̣̣̣̣Completed(this, new InsertSummarỵ̣̣̣̣̣̣̣CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorInfo CreateError(ErrorInfo errorInfo, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] content) {
            object[] results = this.Invoke("CreateError", new object[] {
                        errorInfo,
                        content});
            return ((ErrorInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CreateErrorAsync(ErrorInfo errorInfo, byte[] content) {
            this.CreateErrorAsync(errorInfo, content, null);
        }
        
        /// <remarks/>
        public void CreateErrorAsync(ErrorInfo errorInfo, byte[] content, object userState) {
            if ((this.CreateErrorOperationCompleted == null)) {
                this.CreateErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateErrorOperationCompleted);
            }
            this.InvokeAsync("CreateError", new object[] {
                        errorInfo,
                        content}, this.CreateErrorOperationCompleted, userState);
        }
        
        private void OnCreateErrorOperationCompleted(object arg) {
            if ((this.CreateErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateErrorCompleted(this, new CreateErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMaxRequestLength", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetMaxRequestLength() {
            object[] results = this.Invoke("GetMaxRequestLength", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetMaxRequestLengthAsync() {
            this.GetMaxRequestLengthAsync(null);
        }
        
        /// <remarks/>
        public void GetMaxRequestLengthAsync(object userState) {
            if ((this.GetMaxRequestLengthOperationCompleted == null)) {
                this.GetMaxRequestLengthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMaxRequestLengthOperationCompleted);
            }
            this.InvokeAsync("GetMaxRequestLength", new object[0], this.GetMaxRequestLengthOperationCompleted, userState);
        }
        
        private void OnGetMaxRequestLengthOperationCompleted(object arg) {
            if ((this.GetMaxRequestLengthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMaxRequestLengthCompleted(this, new GetMaxRequestLengthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertSummaryInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertSummaryInfo(ErrorShortInfo summaries) {
            object[] results = this.Invoke("InsertSummaryInfo", new object[] {
                        summaries});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertSummaryInfoAsync(ErrorShortInfo summaries) {
            this.InsertSummaryInfoAsync(summaries, null);
        }
        
        /// <remarks/>
        public void InsertSummaryInfoAsync(ErrorShortInfo summaries, object userState) {
            if ((this.InsertSummaryInfoOperationCompleted == null)) {
                this.InsertSummaryInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertSummaryInfoOperationCompleted);
            }
            this.InvokeAsync("InsertSummaryInfo", new object[] {
                        summaries}, this.InsertSummaryInfoOperationCompleted, userState);
        }
        
        private void OnInsertSummaryInfoOperationCompleted(object arg) {
            if ((this.InsertSummaryInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertSummaryInfoCompleted(this, new InsertSummaryInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorShortInfo {
        
        private string errorIdField;
        
        private SummaryItem[] summaryField;
        
        /// <remarks/>
        public string ErrorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
            }
        }
        
        /// <remarks/>
        public SummaryItem[] Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SummaryItem {
        
        private string keyField;
        
        private object valueField;
        
        private string dataTypeField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorFileInfo {
        
        private int fileIdField;
        
        private string fileNameField;
        
        /// <remarks/>
        public int FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorFiles {
        
        private string errorIdField;
        
        private ErrorFileInfo[] errorFilesInfoField;
        
        /// <remarks/>
        public string ErrorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
            }
        }
        
        /// <remarks/>
        public ErrorFileInfo[] ErrorFilesInfo {
            get {
                return this.errorFilesInfoField;
            }
            set {
                this.errorFilesInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorInfo {
        
        private string errorIdField;
        
        private string folderNameField;
        
        private string metaZipFileField;
        
        private bool isDeletedField;
        
        private bool isDownloadedField;
        
        private System.DateTime creationDateField;
        
        private int typeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string ErrorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
            }
        }
        
        /// <remarks/>
        public string FolderName {
            get {
                return this.folderNameField;
            }
            set {
                this.folderNameField = value;
            }
        }
        
        /// <remarks/>
        public string MetaZipFile {
            get {
                return this.metaZipFileField;
            }
            set {
                this.metaZipFileField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDownloaded {
            get {
                return this.isDownloadedField;
            }
            set {
                this.isDownloadedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorSumaryListCompletedEventHandler(object sender, GetErrorSumaryListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorSumaryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorSumaryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorShortInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorShortInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorListByFieldCompletedEventHandler(object sender, GetErrorListByFieldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorListByFieldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorListByFieldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorShortInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorShortInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorListByFieldsCompletedEventHandler(object sender, GetErrorListByFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorListByFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorListByFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorShortInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorShortInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorInfoCompletedEventHandler(object sender, GetErrorInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorFilesCompletedEventHandler(object sender, GetErrorFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorFiles Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorFiles)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorSumaryListByDateCompletedEventHandler(object sender, GetErrorSumaryListByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorSumaryListByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorSumaryListByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorShortInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorShortInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorSumaryListByTypeCompletedEventHandler(object sender, GetErrorSumaryListByTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorSumaryListByTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorSumaryListByTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorShortInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorShortInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorSumaryListByCustomerCompletedEventHandler(object sender, GetErrorSumaryListByCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorSumaryListByCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorSumaryListByCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorShortInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorShortInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetErrorSumaryListByWhereClauseCompletedEventHandler(object sender, GetErrorSumaryListByWhereClauseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorSumaryListByWhereClauseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorSumaryListByWhereClauseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorShortInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorShortInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetXmlFileCompletedEventHandler(object sender, GetXmlFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXmlFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXmlFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UploadXmlFileCompletedEventHandler(object sender, UploadXmlFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadXmlFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadXmlFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DowloadErrorFileCompletedEventHandler(object sender, DowloadErrorFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DowloadErrorFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DowloadErrorFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void UploadErrorFileCompletedEventHandler(object sender, UploadErrorFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadErrorFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadErrorFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void MoveErrorToTrashCompletedEventHandler(object sender, MoveErrorToTrashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveErrorToTrashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoveErrorToTrashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void MoveErrorToTrash2CompletedEventHandler(object sender, MoveErrorToTrash2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveErrorToTrash2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MoveErrorToTrash2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DeleteErrorCompletedEventHandler(object sender, DeleteErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void DeleteError2CompletedEventHandler(object sender, DeleteError2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteError2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteError2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void InsertErrorCompletedEventHandler(object sender, InsertErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void InsertErrorFileInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void InsertSummarỵ̣̣̣̣̣̣̣CompletedEventHandler(object sender, InsertSummarỵ̣̣̣̣̣̣̣CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertSummarỵ̣̣̣̣̣̣̣CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertSummarỵ̣̣̣̣̣̣̣CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void CreateErrorCompletedEventHandler(object sender, CreateErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetMaxRequestLengthCompletedEventHandler(object sender, GetMaxRequestLengthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMaxRequestLengthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMaxRequestLengthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void InsertSummaryInfoCompletedEventHandler(object sender, InsertSummaryInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertSummaryInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertSummaryInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591