//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.ResourcesManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Forms.ResourcesManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap application_delete {
            get {
                object obj = ResourceManager.GetObject("application_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_edit {
            get {
                object obj = ResourceManager.GetObject("application_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_lightning {
            get {
                object obj = ResourceManager.GetObject("application_lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blog {
            get {
                object obj = ResourceManager.GetObject("blog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disconnect {
            get {
                object obj = ResourceManager.GetObject("disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drive_disk {
            get {
                object obj = ResourceManager.GetObject("drive_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fader {
            get {
                object obj = ResourceManager.GetObject("fader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gtk_cancel {
            get {
                object obj = ResourceManager.GetObject("gtk_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap language {
            get {
                object obj = ResourceManager.GetObject("language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout {
            get {
                object obj = ResourceManager.GetObject("layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_select_footer {
            get {
                object obj = ResourceManager.GetObject("layout_select_footer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap safe {
            get {
                object obj = ResourceManager.GetObject("safe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_checkbox {
            get {
                object obj = ResourceManager.GetObject("vienna_checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_closebutton {
            get {
                object obj = ResourceManager.GetObject("vienna_closebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_combo {
            get {
                object obj = ResourceManager.GetObject("vienna_combo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_command {
            get {
                object obj = ResourceManager.GetObject("vienna_command", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_FrameBottom {
            get {
                object obj = ResourceManager.GetObject("vienna_FrameBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_FrameLeft {
            get {
                object obj = ResourceManager.GetObject("vienna_FrameLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_FrameRight {
            get {
                object obj = ResourceManager.GetObject("vienna_FrameRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_FrameTop {
            get {
                object obj = ResourceManager.GetObject("vienna_FrameTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_header {
            get {
                object obj = ResourceManager.GetObject("vienna_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_helpbutton {
            get {
                object obj = ResourceManager.GetObject("vienna_helpbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_maxbutton {
            get {
                object obj = ResourceManager.GetObject("vienna_maxbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_minbutton {
            get {
                object obj = ResourceManager.GetObject("vienna_minbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_Progress {
            get {
                object obj = ResourceManager.GetObject("vienna_Progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_radiobutton {
            get {
                object obj = ResourceManager.GetObject("vienna_radiobutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_restorebutton {
            get {
                object obj = ResourceManager.GetObject("vienna_restorebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_ScrollHorzArrow {
            get {
                object obj = ResourceManager.GetObject("vienna_ScrollHorzArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_ScrollHorzShaft {
            get {
                object obj = ResourceManager.GetObject("vienna_ScrollHorzShaft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_ScrollHorzThumb {
            get {
                object obj = ResourceManager.GetObject("vienna_ScrollHorzThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_ScrollVertArrow {
            get {
                object obj = ResourceManager.GetObject("vienna_ScrollVertArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_ScrollVertShaft {
            get {
                object obj = ResourceManager.GetObject("vienna_ScrollVertShaft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_ScrollVertThumb {
            get {
                object obj = ResourceManager.GetObject("vienna_ScrollVertThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_spin {
            get {
                object obj = ResourceManager.GetObject("vienna_spin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_Tab {
            get {
                object obj = ResourceManager.GetObject("vienna_Tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_thumb {
            get {
                object obj = ResourceManager.GetObject("vienna_thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vienna_Track {
            get {
                object obj = ResourceManager.GetObject("vienna_Track", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_closebutton {
            get {
                object obj = ResourceManager.GetObject("vista_blue_closebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_FrameBottom {
            get {
                object obj = ResourceManager.GetObject("vista_blue_FrameBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_FrameLeft {
            get {
                object obj = ResourceManager.GetObject("vista_blue_FrameLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_FrameRight {
            get {
                object obj = ResourceManager.GetObject("vista_blue_FrameRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_FrameTop {
            get {
                object obj = ResourceManager.GetObject("vista_blue_FrameTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_helpbutton {
            get {
                object obj = ResourceManager.GetObject("vista_blue_helpbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_maxbutton {
            get {
                object obj = ResourceManager.GetObject("vista_blue_maxbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_minbutton {
            get {
                object obj = ResourceManager.GetObject("vista_blue_minbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_restorebutton {
            get {
                object obj = ResourceManager.GetObject("vista_blue_restorebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_blue_Tab {
            get {
                object obj = ResourceManager.GetObject("vista_blue_Tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_checkbox {
            get {
                object obj = ResourceManager.GetObject("vista_checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_closebutton {
            get {
                object obj = ResourceManager.GetObject("vista_closebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_combo {
            get {
                object obj = ResourceManager.GetObject("vista_combo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_command {
            get {
                object obj = ResourceManager.GetObject("vista_command", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_FrameBottom {
            get {
                object obj = ResourceManager.GetObject("vista_FrameBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_FrameLeft {
            get {
                object obj = ResourceManager.GetObject("vista_FrameLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_FrameRight {
            get {
                object obj = ResourceManager.GetObject("vista_FrameRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_FrameTop {
            get {
                object obj = ResourceManager.GetObject("vista_FrameTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_header {
            get {
                object obj = ResourceManager.GetObject("vista_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_helpbutton {
            get {
                object obj = ResourceManager.GetObject("vista_helpbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_maxbutton {
            get {
                object obj = ResourceManager.GetObject("vista_maxbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_minbutton {
            get {
                object obj = ResourceManager.GetObject("vista_minbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_Progress {
            get {
                object obj = ResourceManager.GetObject("vista_Progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_radiobutton {
            get {
                object obj = ResourceManager.GetObject("vista_radiobutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_restorebutton {
            get {
                object obj = ResourceManager.GetObject("vista_restorebutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_ScrollHorzArrow {
            get {
                object obj = ResourceManager.GetObject("vista_ScrollHorzArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_ScrollHorzShaft {
            get {
                object obj = ResourceManager.GetObject("vista_ScrollHorzShaft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_ScrollHorzThumb {
            get {
                object obj = ResourceManager.GetObject("vista_ScrollHorzThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_ScrollVertArrow {
            get {
                object obj = ResourceManager.GetObject("vista_ScrollVertArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_ScrollVertShaft {
            get {
                object obj = ResourceManager.GetObject("vista_ScrollVertShaft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_ScrollVertThumb {
            get {
                object obj = ResourceManager.GetObject("vista_ScrollVertThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_spin {
            get {
                object obj = ResourceManager.GetObject("vista_spin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_Tab {
            get {
                object obj = ResourceManager.GetObject("vista_Tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_thumb {
            get {
                object obj = ResourceManager.GetObject("vista_thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vista_Track {
            get {
                object obj = ResourceManager.GetObject("vista_Track", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vPortal {
            get {
                object obj = ResourceManager.GetObject("vPortal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vportal_package {
            get {
                object obj = ResourceManager.GetObject("vportal_package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
